// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEcSOPPJwWvzd162KbgHDwfNA6dk1sQyk',
    appId: '1:194101384075:web:755f61cdd2d752d2a1158e',
    messagingSenderId: '194101384075',
    projectId: 'lab09-d80e7',
    authDomain: 'lab09-d80e7.firebaseapp.com',
    storageBucket: 'lab09-d80e7.appspot.com',
    measurementId: 'G-D95XDEHVXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_-kvG13LvWBST-Tn3fI76jiPCzLJuz-w',
    appId: '1:194101384075:android:36f4792288c9e06fa1158e',
    messagingSenderId: '194101384075',
    projectId: 'lab09-d80e7',
    storageBucket: 'lab09-d80e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTSGb9wjVs58NFajUgSU2EmOS7XLzReeI',
    appId: '1:194101384075:ios:5901454eddfdafe3a1158e',
    messagingSenderId: '194101384075',
    projectId: 'lab09-d80e7',
    storageBucket: 'lab09-d80e7.appspot.com',
    iosClientId: '194101384075-d3b3hotsvum0hkhcqoe5k80stp5lievq.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab09',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTSGb9wjVs58NFajUgSU2EmOS7XLzReeI',
    appId: '1:194101384075:ios:5901454eddfdafe3a1158e',
    messagingSenderId: '194101384075',
    projectId: 'lab09-d80e7',
    storageBucket: 'lab09-d80e7.appspot.com',
    iosClientId: '194101384075-d3b3hotsvum0hkhcqoe5k80stp5lievq.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab09',
  );
}
